### ISSUE TITLE
Uninitialized String Error

### ISSUE THREAD

**Issue by ssatz** [JsonMapper/LaravelPackage#20]
**Describe the bug**
String and Object are not mapping in Laravel 10

**To Reproduce**
```
$mapper = app()->get(\JsonMapper\LaravelPackage\JsonMapperInterface::class);
$data = $mapper->mapObjectFromString('{"id":"cont_LaVWvuJQsuRCJ1","entity":"contact","name":"sathish","contact":null,"email":"sathish@gmail.com","type":"customer","reference_id":null,"batch_id":null,"active":true,"notes":[],"created_at":1680784501}',new \OptimoApps\RazorPayX\Entity\Contact());
dd($data);
```

**Expected behavior**
```
OptimoApps\RazorPayX\Entity\Contact {#9799
  +id: "cont_F0pv1KbaqMZbXm"
  +entity: "contact"
  +name: "Gaurav Kumar"
  +contact: "9123456789"
  +email: "gaurav.kumar@example.com"
  +type: "employee"
  +reference_id: "Acme Contact ID 12345"
  +batch_id: null
  +active: true
  +notes: array:2 [
    "notes_key_1" => "Tea, Earl Grey, Hot"
    "notes_key_2" => "Tea, Earl Grey… decaf."
  ]
  +created_at: 1591773539
}

```
**Stacktrace**
`object(OptimoApps\RazorPayX\Entity\Contact)#1537 (0) { ["id"]=> uninitialized(string) ["entity"]=> uninitialized(?string) ["name"]=> uninitialized(?string) ["contact"]=> uninitialized(?string) ["email"]=> uninitialized(?string) ["type"]=> uninitialized(?string) ["reference_id"]=> uninitialized(?string) ["batch_id"]=> uninitialized(?string) ["active"]=> uninitialized(bool) ["notes"]=> uninitialized(array) ["created_at"]=> uninitialized(int) ["from"]=> uninitialized(int) ["to"]=> uninitialized(int) ["count"]=> uninitialized(int) ["skip"]=> uninitialized(int) }`

**Environment (please complete the following information):**
 - PHP: 8.1
 
**Additional context**
This was working in laravel 9

**Comment by ssatz** [comment]
Update: Where as below code is working without using the Laravel Package

```
$mapper = \JsonMapper\JsonMapperBuilder::new()
    ->withDocBlockAnnotationsMiddleware()
    ->withTypedPropertiesMiddleware()
    ->build();
$data = $mapper->mapObjectFromString('{"id":"cont_LaVWvuJQsuRCJ1","entity":"contact","name":"sathish","contact":null,"email":"sathish@gmail.com","type":"customer","reference_id":null,"batch_id":null,"active":true,"notes":[],"created_at":1680784501}',new \OptimoApps\RazorPayX\Entity\Contact());
dd($data);
```

**Comment by DannyvdSluijs** [comment]
Hi thanks for reporting the issue. Quick question what is in the file  ./config/json-mapper.php
As it seems you’re missing the TypedProperties middleware. 

As you can read on https://dev.to/dannyvdsluijs/mapping-json-to-php-object-using-jsonmapper-41lg the settings should be best-fit to include the TypedProperties middleware.

**Comment by ssatz** [comment]
@DannyvdSluijs Never mind! My bad missed json-mapper.php config file for my package.
